# Generated by Django 3.0.8 on 2020-07-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200728_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='following',
        ),
    ]
